Music search query history
BimmerGestalt/AAIdrive pull request #567
Opened 2022-04-29 05:44 UTC by Ben2356

My long overdue PR for this that I've been working on off and on 😅! This adds the saving a simple history of the queries that the user has previously searched. In order to have a query be saved the user must either 1) click Play from Search, 2) click View Full Results or the ellipsis entry, 3) click on a previous search history query, 4) click on a search result item, 5) click on the OK button to bring up the full page search results . The search history query saves the last 8 searches, the most recent of the search queries being displayed at the bottom of the list. 

Additionally with this feature the search logic has been refactored/updated to help prevent race conditions when displaying search results in the suggestion list and help smoothen out the experience.

I wasn't able to get any videos / pictures of this one but didn't want to hold this up any longer, sorry about that.

2022-04-29 15:31 UTC, hufman commented
Please merge the latest main branch, which should include a fix for running the CI tests in a Pull Request context!

2022-04-29 15:33 UTC, hufman requested changes

2022-04-29 15:33 UTC, hufman commented on app/src/test/java/me/hufman/androidautoidrive/music/MusicAppTest.kt
> +	fun testSearch_MultipleSearchJobs() {
Thank you for adding tests for this tricky piece of code!

2022-05-02 06:19 UTC, Ben2356 commented
> Please merge the latest main branch, which should include a fix for running the CI tests in a Pull Request context!

Merged the latest!

2022-05-02 06:38 UTC, Ben2356 commented on app/src/test/java/me/hufman/androidautoidrive/music/MusicAppTest.kt
> +		on { appSettings } doReturn MockAppSettingsReceiver(mock())
Ah you're right, not sure why I didn't update the type of the `MusicController.appSettings` and instead went this route. Thanks for pointing that out

2022-05-02 06:54 UTC, Ben2356 commented on app/src/main/java/me/hufman/androidautoidrive/carapp/music/views/SearchInputView.kt
> +				searchQueryHistory.add(input)
Yeah, I was originally was using the top of the list as the method docs state but changed this when I was experimenting with the suggest model and never updated it back. Updated to move latest queries to the top of the list

2022-05-03 05:47 UTC, hufman approved these changes

2022-05-03 05:47 UTC, merged